#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: f35655a
#
Name     : perl-Image-Xbm
Version  : 1.11
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Image-Xbm-1.11.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Image-Xbm-1.11.tar.gz
Summary  : 'Load, create, manipulate and save xbm image files.'
Group    : Development/Tools
License  : LGPL-2.0
Requires: perl-Image-Xbm-perl = %{version}-%{release}
Requires: perl(Image::Base)
BuildRequires : buildreq-cpan
BuildRequires : perl(Image::Base)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=head1 NAME
Image::Xbm - Load, create, manipulate and save xbm image files.
=head1 SYNOPSIS

%package dev
Summary: dev components for the perl-Image-Xbm package.
Group: Development
Provides: perl-Image-Xbm-devel = %{version}-%{release}
Requires: perl-Image-Xbm = %{version}-%{release}

%description dev
dev components for the perl-Image-Xbm package.


%package perl
Summary: perl components for the perl-Image-Xbm package.
Group: Default
Requires: perl-Image-Xbm = %{version}-%{release}

%description perl
perl components for the perl-Image-Xbm package.


%prep
%setup -q -n Image-Xbm-1.11
cd %{_builddir}/Image-Xbm-1.11
pushd ..
cp -a Image-Xbm-1.11 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Image::Xbm.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
